// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch'
import type {
  AuthTokenV1AuthLoginPostData,
  AuthTokenV1AuthLoginPostError,
  AuthTokenV1AuthLoginPostResponse,
  VerifyTokenV1AuthVerifyPostData,
  VerifyTokenV1AuthVerifyPostError,
  VerifyTokenV1AuthVerifyPostResponse,
  GetFileListV1FileListGetData,
  GetFileListV1FileListGetError,
  GetFileListV1FileListGetResponse,
  CreateFileV1FileCreatePostData,
  CreateFileV1FileCreatePostError,
  CreateFileV1FileCreatePostResponse,
  DeleteFileV1FileDeleteDeleteData,
  DeleteFileV1FileDeleteDeleteError,
  DeleteFileV1FileDeleteDeleteResponse,
  InstallNonebotModuleV1StoreNonebotInstallPostData,
  InstallNonebotModuleV1StoreNonebotInstallPostError,
  InstallNonebotModuleV1StoreNonebotInstallPostResponse,
  UninstallNonebotModuleV1StoreNonebotUninstallPostData,
  UninstallNonebotModuleV1StoreNonebotUninstallPostError,
  UninstallNonebotModuleV1StoreNonebotUninstallPostResponse,
  GetNonebotStoreItemsV1StoreNonebotListGetData,
  GetNonebotStoreItemsV1StoreNonebotListGetError,
  GetNonebotStoreItemsV1StoreNonebotListGetResponse,
  SearchNonebotStoreItemV1StoreNonebotSearchPostData,
  SearchNonebotStoreItemV1StoreNonebotSearchPostError,
  SearchNonebotStoreItemV1StoreNonebotSearchPostResponse,
  RunProcessV1ProcessRunPostData,
  RunProcessV1ProcessRunPostError,
  RunProcessV1ProcessRunPostResponse,
  StopProcessV1ProcessStopPostData,
  StopProcessV1ProcessStopPostError,
  StopProcessV1ProcessStopPostResponse,
  WriteToProcessV1ProcessWritePostData,
  WriteToProcessV1ProcessWritePostError,
  WriteToProcessV1ProcessWritePostResponse,
  GetLogHistoryV1ProcessLogHistoryGetData,
  GetLogHistoryV1ProcessLogHistoryGetError,
  GetLogHistoryV1ProcessLogHistoryGetResponse,
  GetProjectEnvListV1ProjectConfigEnvListGetData,
  GetProjectEnvListV1ProjectConfigEnvListGetError,
  GetProjectEnvListV1ProjectConfigEnvListGetResponse,
  CreateProjectEnvV1ProjectConfigEnvCreatePostData,
  CreateProjectEnvV1ProjectConfigEnvCreatePostError,
  CreateProjectEnvV1ProjectConfigEnvCreatePostResponse,
  DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteData,
  DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteError,
  DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteResponse,
  UseProjectEnvV1ProjectConfigEnvUsePostData,
  UseProjectEnvV1ProjectConfigEnvUsePostError,
  UseProjectEnvV1ProjectConfigEnvUsePostResponse,
  GetProjectMetaConfigV1ProjectConfigMetaDetailGetData,
  GetProjectMetaConfigV1ProjectConfigMetaDetailGetError,
  GetProjectMetaConfigV1ProjectConfigMetaDetailGetResponse,
  GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetData,
  GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetError,
  GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetResponse,
  GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetData,
  GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetError,
  GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetResponse,
  UpdateProjectConfigV1ProjectConfigUpdatePostData,
  UpdateProjectConfigV1ProjectConfigUpdatePostError,
  UpdateProjectConfigV1ProjectConfigUpdatePostResponse,
  GetDotenvFileV1ProjectConfigDotenvGetData,
  GetDotenvFileV1ProjectConfigDotenvGetError,
  GetDotenvFileV1ProjectConfigDotenvGetResponse,
  UpdateDotenvFileV1ProjectConfigDotenvPutData,
  UpdateDotenvFileV1ProjectConfigDotenvPutError,
  UpdateDotenvFileV1ProjectConfigDotenvPutResponse,
  CreateProjectV1ProjectCreatePostData,
  CreateProjectV1ProjectCreatePostError,
  CreateProjectV1ProjectCreatePostResponse,
  AddProjectV1ProjectAddPostData,
  AddProjectV1ProjectAddPostError,
  AddProjectV1ProjectAddPostResponse,
  GetProjectProfileV1ProjectProfileGetData,
  GetProjectProfileV1ProjectProfileGetError,
  GetProjectProfileV1ProjectProfileGetResponse,
  DeleteProjectV1ProjectDeleteDeleteData,
  DeleteProjectV1ProjectDeleteDeleteError,
  DeleteProjectV1ProjectDeleteDeleteResponse,
  ListProjectV1ProjectListGetError,
  ListProjectV1ProjectListGetResponse,
  CheckProjectTomlV1ProjectCheckTomlPostData,
  CheckProjectTomlV1ProjectCheckTomlPostError,
  CheckProjectTomlV1ProjectCheckTomlPostResponse
} from './types.gen'

export const client = createClient(createConfig())

export class AuthService {
  /**
   * Auth Token
   * - 登录, 成功后返回 JWT 密钥
   */
  public static authTokenV1AuthLoginPost<ThrowOnError extends boolean = false>(
    options: Options<AuthTokenV1AuthLoginPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      AuthTokenV1AuthLoginPostResponse,
      AuthTokenV1AuthLoginPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/auth/login'
    })
  }

  /**
   * Verify Token
   * - 验证 JWT 密钥是否可用, 返回到期时间戳
   */
  public static verifyTokenV1AuthVerifyPost<ThrowOnError extends boolean = false>(
    options: Options<VerifyTokenV1AuthVerifyPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      VerifyTokenV1AuthVerifyPostResponse,
      VerifyTokenV1AuthVerifyPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/auth/verify'
    })
  }
}

export class FileService {
  /**
   * Get File List
   * - 根据提供的路径, 基于 base_dir 返回文件列表
   */
  public static getFileListV1FileListGet<ThrowOnError extends boolean = false>(
    options: Options<GetFileListV1FileListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetFileListV1FileListGetResponse,
      GetFileListV1FileListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/list'
    })
  }

  /**
   * Create File
   * - 根据提供的路径, 基于 base_dir 创建文件
   */
  public static createFileV1FileCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateFileV1FileCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateFileV1FileCreatePostResponse,
      CreateFileV1FileCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/create'
    })
  }

  /**
   * Delete File
   * - 根据提供的路径, 基于 base_dir 删除文件
   */
  public static deleteFileV1FileDeleteDelete<ThrowOnError extends boolean = false>(
    options: Options<DeleteFileV1FileDeleteDeleteData, ThrowOnError>
  ) {
    return (options?.client ?? client).delete<
      DeleteFileV1FileDeleteDeleteResponse,
      DeleteFileV1FileDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/delete'
    })
  }
}

export class StoreService {
  /**
   *  Install Nonebot Module
   * - 安装模块至 NoneBot 实例
   */
  public static installNonebotModuleV1StoreNonebotInstallPost<ThrowOnError extends boolean = false>(
    options: Options<InstallNonebotModuleV1StoreNonebotInstallPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      InstallNonebotModuleV1StoreNonebotInstallPostResponse,
      InstallNonebotModuleV1StoreNonebotInstallPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/install'
    })
  }

  /**
   *  Uninstall Nonebot Module
   * - 卸载 NoneBot 实例中的模块
   */
  public static uninstallNonebotModuleV1StoreNonebotUninstallPost<
    ThrowOnError extends boolean = false
  >(options: Options<UninstallNonebotModuleV1StoreNonebotUninstallPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      UninstallNonebotModuleV1StoreNonebotUninstallPostResponse,
      UninstallNonebotModuleV1StoreNonebotUninstallPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/uninstall'
    })
  }

  /**
   *  Get Nonebot Store Items
   * - 获取 NoneBot Store 中的模块列表
   */
  public static getNonebotStoreItemsV1StoreNonebotListGet<ThrowOnError extends boolean = false>(
    options: Options<GetNonebotStoreItemsV1StoreNonebotListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetNonebotStoreItemsV1StoreNonebotListGetResponse,
      GetNonebotStoreItemsV1StoreNonebotListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/list'
    })
  }

  /**
   * Search Nonebot Store Item
   * - 搜索 NoneBot Store 中的模块
   */
  public static searchNonebotStoreItemV1StoreNonebotSearchPost<
    ThrowOnError extends boolean = false
  >(options: Options<SearchNonebotStoreItemV1StoreNonebotSearchPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      SearchNonebotStoreItemV1StoreNonebotSearchPostResponse,
      SearchNonebotStoreItemV1StoreNonebotSearchPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/search'
    })
  }
}

export class ProcessService {
  /**
   * Run Process
   * - 运行 NoneBot 实例
   */
  public static runProcessV1ProcessRunPost<ThrowOnError extends boolean = false>(
    options: Options<RunProcessV1ProcessRunPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      RunProcessV1ProcessRunPostResponse,
      RunProcessV1ProcessRunPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/run'
    })
  }

  /**
   *  Stop Process
   * - 终止 NoneBot 实例
   */
  public static stopProcessV1ProcessStopPost<ThrowOnError extends boolean = false>(
    options: Options<StopProcessV1ProcessStopPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      StopProcessV1ProcessStopPostResponse,
      StopProcessV1ProcessStopPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/stop'
    })
  }

  /**
   * Write To Process
   * - 向 NoneBot 实例进程写入数据
   */
  public static writeToProcessV1ProcessWritePost<ThrowOnError extends boolean = false>(
    options: Options<WriteToProcessV1ProcessWritePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      WriteToProcessV1ProcessWritePostResponse,
      WriteToProcessV1ProcessWritePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/write'
    })
  }

  /**
   * Get Log History
   * - 获取历史进程日志
   */
  public static getLogHistoryV1ProcessLogHistoryGet<ThrowOnError extends boolean = false>(
    options: Options<GetLogHistoryV1ProcessLogHistoryGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetLogHistoryV1ProcessLogHistoryGetResponse,
      GetLogHistoryV1ProcessLogHistoryGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/log/history'
    })
  }
}

export class ProjectService {
  /**
   *  Get Project Env List
   * - 获取 NoneBot 实例中的环境文件列表
   */
  public static getProjectEnvListV1ProjectConfigEnvListGet<ThrowOnError extends boolean = false>(
    options: Options<GetProjectEnvListV1ProjectConfigEnvListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetProjectEnvListV1ProjectConfigEnvListGetResponse,
      GetProjectEnvListV1ProjectConfigEnvListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/list'
    })
  }

  /**
   *  Create Project Env
   * - 创建 NoneBot 实例中的环境文件
   */
  public static createProjectEnvV1ProjectConfigEnvCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateProjectEnvV1ProjectConfigEnvCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateProjectEnvV1ProjectConfigEnvCreatePostResponse,
      CreateProjectEnvV1ProjectConfigEnvCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/create'
    })
  }

  /**
   *  Delete Project Env
   * - 删除 NoneBot 实例中的环境文件
   */
  public static deleteProjectEnvV1ProjectConfigEnvDeleteDelete<
    ThrowOnError extends boolean = false
  >(options: Options<DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteData, ThrowOnError>) {
    return (options?.client ?? client).delete<
      DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteResponse,
      DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/delete'
    })
  }

  /**
   *  Use Project Env
   * - 切换 NoneBot 实例所应用的环境文件
   */
  public static useProjectEnvV1ProjectConfigEnvUsePost<ThrowOnError extends boolean = false>(
    options: Options<UseProjectEnvV1ProjectConfigEnvUsePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      UseProjectEnvV1ProjectConfigEnvUsePostResponse,
      UseProjectEnvV1ProjectConfigEnvUsePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/use'
    })
  }

  /**
   *  Get Project Meta Config
   * - 获取 NoneBot 实例在 .toml 中的配置信息
   */
  public static getProjectMetaConfigV1ProjectConfigMetaDetailGet<
    ThrowOnError extends boolean = false
  >(options: Options<GetProjectMetaConfigV1ProjectConfigMetaDetailGetData, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetProjectMetaConfigV1ProjectConfigMetaDetailGetResponse,
      GetProjectMetaConfigV1ProjectConfigMetaDetailGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/meta/detail'
    })
  }

  /**
   *  Get Project Nonebot Config
   * - 获取 NoneBot 实例配置信息
   */
  public static getProjectNonebotConfigV1ProjectConfigNonebotDetailGet<
    ThrowOnError extends boolean = false
  >(options: Options<GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetData, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetResponse,
      GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/nonebot/detail'
    })
  }

  /**
   *  Get Project Nonebot Plugin Config
   * - 获取 NoneBot 实例中所有 NoneBot 插件设置信息
   */
  public static getProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGet<
    ThrowOnError extends boolean = false
  >(
    options: Options<
      GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetData,
      ThrowOnError
    >
  ) {
    return (options?.client ?? client).get<
      GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetResponse,
      GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/nonebot/plugin/detail'
    })
  }

  /**
   *  Update Project Config
   * - 根据模块类型及环境更新配置信息
   * - 说明:
   * * `module_type` 仅作 WebUI 更新自身存储的实例信息，不会影响实例本体
   */
  public static updateProjectConfigV1ProjectConfigUpdatePost<ThrowOnError extends boolean = false>(
    options: Options<UpdateProjectConfigV1ProjectConfigUpdatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      UpdateProjectConfigV1ProjectConfigUpdatePostResponse,
      UpdateProjectConfigV1ProjectConfigUpdatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/update'
    })
  }

  /**
   * Get Dotenv File
   * - 获取环境文件内容
   */
  public static getDotenvFileV1ProjectConfigDotenvGet<ThrowOnError extends boolean = false>(
    options: Options<GetDotenvFileV1ProjectConfigDotenvGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetDotenvFileV1ProjectConfigDotenvGetResponse,
      GetDotenvFileV1ProjectConfigDotenvGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/dotenv'
    })
  }

  /**
   * Update Dotenv File
   * - 更新环境文件内容
   */
  public static updateDotenvFileV1ProjectConfigDotenvPut<ThrowOnError extends boolean = false>(
    options: Options<UpdateDotenvFileV1ProjectConfigDotenvPutData, ThrowOnError>
  ) {
    return (options?.client ?? client).put<
      UpdateDotenvFileV1ProjectConfigDotenvPutResponse,
      UpdateDotenvFileV1ProjectConfigDotenvPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/dotenv'
    })
  }

  /**
   * Create Project
   * - 创建 NoneBot 实例
   * - 返回对应的日志密钥, 用于日志展现
   */
  public static createProjectV1ProjectCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateProjectV1ProjectCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateProjectV1ProjectCreatePostResponse,
      CreateProjectV1ProjectCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/create'
    })
  }

  /**
   * Add Project
   * - 添加 NoneBot 实例
   * - 返回对应的日志密钥, 用于日志展现
   */
  public static addProjectV1ProjectAddPost<ThrowOnError extends boolean = false>(
    options: Options<AddProjectV1ProjectAddPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      AddProjectV1ProjectAddPostResponse,
      AddProjectV1ProjectAddPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/add'
    })
  }

  /**
   * Get Project Profile
   * - 获取 NoneBot 实例的配置信息
   */
  public static getProjectProfileV1ProjectProfileGet<ThrowOnError extends boolean = false>(
    options: Options<GetProjectProfileV1ProjectProfileGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetProjectProfileV1ProjectProfileGetResponse,
      GetProjectProfileV1ProjectProfileGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/profile'
    })
  }

  /**
   * Delete Project
   * - 删除 NoneBot 实例
   */
  public static deleteProjectV1ProjectDeleteDelete<ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectV1ProjectDeleteDeleteData, ThrowOnError>
  ) {
    return (options?.client ?? client).delete<
      DeleteProjectV1ProjectDeleteDeleteResponse,
      DeleteProjectV1ProjectDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/delete'
    })
  }

  /**
   * List Project
   * - 获取所有 NoneBot 实例基本信息
   */
  public static listProjectV1ProjectListGet<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ListProjectV1ProjectListGetResponse,
      ListProjectV1ProjectListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/list'
    })
  }

  /**
   * Check Project Toml
   * - 检查 NoneBot 实例的 toml 文件并从中获取所需信息
   */
  public static checkProjectTomlV1ProjectCheckTomlPost<ThrowOnError extends boolean = false>(
    options: Options<CheckProjectTomlV1ProjectCheckTomlPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CheckProjectTomlV1ProjectCheckTomlPostResponse,
      CheckProjectTomlV1ProjectCheckTomlPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/check_toml'
    })
  }
}
