// This file is auto-generated by @hey-api/openapi-ts

export type Adapter = {
  module_name: string
  project_link: string
  name: string
  desc: string
  author: string
  homepage: string
  tags?: Array<ModuleTag>
  is_official: boolean
  is_download?: boolean
}

export type AddProjectData = {
  project_name: string
  project_dir: string
  mirror_url: string
  adapters?: Array<string>
  plugins?: Array<string>
  plugin_dirs?: Array<string>
  builtin_plugins?: Array<string>
}

export type Body_search_nonebot_store_item_v1_store_nonebot_search_post = {
  data: SearchRequest
}

/**
 * An enumeration.
 */
export type ConfigType = 'project' | 'toml'

export type CreateProjectData = {
  is_bootstrap: boolean
  project_name: string
  project_dir: string
  mirror_url: string
  drivers: Array<nb_cli_plugin_webui__app__schemas__ModuleInfo>
  adapters: Array<nb_cli_plugin_webui__app__schemas__ModuleInfo>
  use_src: boolean
}

export type Driver = {
  module_name: string
  project_link: string
  name: string
  desc: string
  author: string
  homepage: string
  tags?: Array<ModuleTag>
  is_official: boolean
  is_download?: boolean
}

export type FileInfo = {
  name: string
  is_dir: boolean
  path: string
  modified_time: string
  absolute_path: string
}

export type FileResponse = {
  detail: Array<FileInfo>
}

export type GenericResponse_List_nb_cli_plugin_webui_app_handlers_process_schemas_ProcessLog__ = {
  detail: Array<ProcessLog>
}

export type GenericResponse_List_str__ = {
  detail: Array<string>
}

export type GenericResponse_NoneBotProjectMeta_ = {
  detail: NoneBotProjectMeta
}

export type GenericResponse_ProjectTomlDetail_ = {
  detail: ProjectTomlDetail
}

export type GenericResponse_int_ = {
  detail: number
}

export type GenericResponse_str_ = {
  detail: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ListProjectResponse = {
  detail: {
    [key: string]: NoneBotProjectMeta
  }
}

/**
 * An enumeration.
 */
export type LogLevel = 'STDOUT' | 'INFO' | 'WARNING' | 'ERROR' | 'DEBUG'

export type LoginRequest = {
  token: string
  mark: string
}

export type ModuleConfigChild = {
  title: string
  description: string
  name: string
  default?: unknown
  conf_type: string
  enum: Array<unknown>
  configured?: unknown
  is_secret: boolean
  latest_change?: string
}

export type ModuleConfigFather = {
  title: string
  description: string
  name: string
  module_type: ModuleType | ConfigType
  properties: Array<ModuleConfigChild>
}

export type ModuleConfigResponse = {
  detail: Array<ModuleConfigFather>
}

export type ModuleConfigUpdateRequest = {
  env: string
  conf_type: string
  k: string
  v?: unknown
}

export type ModuleTag = {
  label: string
  color: string
}

/**
 * An enumeration.
 */
export type ModuleType = 'plugin' | 'adapter' | 'driver'

export type NoneBotProjectMeta = {
  project_id: string
  project_name: string
  project_dir: string
  mirror_url: string
  adapters: Array<nb_cli_plugin_webui__app__schemas__ModuleInfo>
  drivers: Array<nb_cli_plugin_webui__app__schemas__ModuleInfo>
  plugins: Array<nb_cli_plugin_webui__app__schemas__Plugin>
  plugin_dirs: Array<string>
  builtin_plugins: Array<string>
  is_running?: boolean
  use_env?: string
  use_run_script?: boolean
  run_script_name?: string
}

export type ProcessLog = {
  time?: string
  level?: LogLevel
  message: string
}

export type ProjectTomlDetail = {
  project_name: string
  adapters: Array<{
    [key: string]: string
  }>
  plugins: Array<string>
  plugin_dirs: Array<string>
  builtin_plugins: Array<string>
}

export type SearchRequest = {
  module_type: ModuleType
  tags?: Array<nb_cli_plugin_webui__app__schemas__SearchTag>
  content: string
}

export type SimpleModel = {
  name: string
  is_dir: boolean
  path: string
}

export type StoreListResponse = {
  detail: Array<nb_cli_plugin_webui__app__schemas__Plugin> | Array<Adapter> | Array<Driver>
  now_page: number
  total_page: number
  total_item: number
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type VerifyRequest = {
  jwt_token: string
}

/**
 * An enumeration.
 */
export type nb_cli_plugin_webui__app__constants__SearchTag =
  | 'official'
  | 'valid'
  | 'latest'
  | 'downloaded'
  | 'author'
  | 'tag'

export type nb_cli_plugin_webui__app__schemas__ModuleInfo = {
  module_name: string
  project_link: string
  name: string
  desc: string
  author: string
  homepage: string
  tags?: Array<ModuleTag>
  is_official: boolean
  is_download?: boolean
}

export type nb_cli_plugin_webui__app__schemas__Plugin = {
  module_name: string
  project_link: string
  name: string
  desc: string
  author: string
  homepage: string
  tags?: Array<ModuleTag>
  is_official: boolean
  is_download?: boolean
  type?: string
  supported_adapters?: Array<string>
  valid: boolean
  version: string
  time: string
  skip_test: boolean
  config_detail?: {
    [key: string]: unknown
  }
}

export type nb_cli_plugin_webui__app__schemas__SearchTag = {
  label: nb_cli_plugin_webui__app__constants__SearchTag
  text?: string
}

export type nb_cli_plugin_webui__app__store__schemas__ModuleInfo = {
  module_name: string
  project_link: string
  name: string
  desc: string
  author: string
  homepage: string
  tags?: Array<ModuleTag>
  is_official: boolean
  is_download?: boolean
  module_type: 'module'
}

export type module_type = 'module'

export type nb_cli_plugin_webui__app__store__schemas__Plugin = {
  module_name: string
  project_link: string
  name: string
  desc: string
  author: string
  homepage: string
  tags?: Array<ModuleTag>
  is_official: boolean
  is_download?: boolean
  type?: string
  supported_adapters?: Array<string>
  valid: boolean
  version: string
  time: string
  skip_test: boolean
  config_detail?: {
    [key: string]: unknown
  }
  module_type: 'plugin'
}

export type module_type2 = 'plugin'

export type AuthTokenV1AuthLoginPostData = {
  body: LoginRequest
}

export type AuthTokenV1AuthLoginPostResponse = GenericResponse_str_

export type AuthTokenV1AuthLoginPostError = HTTPValidationError

export type VerifyTokenV1AuthVerifyPostData = {
  body: VerifyRequest
}

export type VerifyTokenV1AuthVerifyPostResponse = GenericResponse_str_

export type VerifyTokenV1AuthVerifyPostError = HTTPValidationError

export type GetFileListV1FileListGetData = {
  query: {
    path: string
  }
}

export type GetFileListV1FileListGetResponse = FileResponse

export type GetFileListV1FileListGetError = HTTPValidationError

export type CreateFileV1FileCreatePostData = {
  body: SimpleModel
}

export type CreateFileV1FileCreatePostResponse = FileResponse

export type CreateFileV1FileCreatePostError = HTTPValidationError

export type DeleteFileV1FileDeleteDeleteData = {
  query: {
    path: string
  }
}

export type DeleteFileV1FileDeleteDeleteResponse = FileResponse

export type DeleteFileV1FileDeleteDeleteError = HTTPValidationError

export type InstallNonebotModuleV1StoreNonebotInstallPostData = {
  body:
    | nb_cli_plugin_webui__app__store__schemas__ModuleInfo
    | nb_cli_plugin_webui__app__store__schemas__Plugin
  query: {
    env: string
    project_id: string
  }
}

export type InstallNonebotModuleV1StoreNonebotInstallPostResponse = GenericResponse_str_

export type InstallNonebotModuleV1StoreNonebotInstallPostError = HTTPValidationError

export type UninstallNonebotModuleV1StoreNonebotUninstallPostData = {
  body:
    | nb_cli_plugin_webui__app__store__schemas__ModuleInfo
    | nb_cli_plugin_webui__app__store__schemas__Plugin
  query: {
    env: string
    project_id: string
  }
}

export type UninstallNonebotModuleV1StoreNonebotUninstallPostResponse = GenericResponse_str_

export type UninstallNonebotModuleV1StoreNonebotUninstallPostError = HTTPValidationError

export type GetNonebotStoreItemsV1StoreNonebotListGetData = {
  query: {
    is_search?: boolean
    module_type: ModuleType
    page: number
    project_id?: string
    show_all?: boolean
  }
}

export type GetNonebotStoreItemsV1StoreNonebotListGetResponse = StoreListResponse

export type GetNonebotStoreItemsV1StoreNonebotListGetError = HTTPValidationError

export type SearchNonebotStoreItemV1StoreNonebotSearchPostData = {
  body: Body_search_nonebot_store_item_v1_store_nonebot_search_post
  query: {
    project_id: string
  }
}

export type SearchNonebotStoreItemV1StoreNonebotSearchPostResponse = StoreListResponse

export type SearchNonebotStoreItemV1StoreNonebotSearchPostError = HTTPValidationError

export type RunProcessV1ProcessRunPostData = {
  query: {
    project_id: string
  }
}

export type RunProcessV1ProcessRunPostResponse = GenericResponse_str_

export type RunProcessV1ProcessRunPostError = HTTPValidationError

export type StopProcessV1ProcessStopPostData = {
  query: {
    project_id: string
  }
}

export type StopProcessV1ProcessStopPostResponse = GenericResponse_str_

export type StopProcessV1ProcessStopPostError = HTTPValidationError

export type WriteToProcessV1ProcessWritePostData = {
  query: {
    content: string
    project_id: string
  }
}

export type WriteToProcessV1ProcessWritePostResponse = GenericResponse_int_

export type WriteToProcessV1ProcessWritePostError = HTTPValidationError

export type GetLogHistoryV1ProcessLogHistoryGetData = {
  query: {
    log_count: number
    log_id: string
  }
}

export type GetLogHistoryV1ProcessLogHistoryGetResponse =
  GenericResponse_List_nb_cli_plugin_webui_app_handlers_process_schemas_ProcessLog__

export type GetLogHistoryV1ProcessLogHistoryGetError = HTTPValidationError

export type GetProjectEnvListV1ProjectConfigEnvListGetData = {
  query: {
    project_id: string
  }
}

export type GetProjectEnvListV1ProjectConfigEnvListGetResponse = GenericResponse_List_str__

export type GetProjectEnvListV1ProjectConfigEnvListGetError = HTTPValidationError

export type CreateProjectEnvV1ProjectConfigEnvCreatePostData = {
  query: {
    env: string
    project_id: string
  }
}

export type CreateProjectEnvV1ProjectConfigEnvCreatePostResponse = GenericResponse_str_

export type CreateProjectEnvV1ProjectConfigEnvCreatePostError = HTTPValidationError

export type DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteData = {
  query: {
    env: string
    project_id: string
  }
}

export type DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteResponse = GenericResponse_str_

export type DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteError = HTTPValidationError

export type UseProjectEnvV1ProjectConfigEnvUsePostData = {
  query: {
    env: string
    project_id: string
  }
}

export type UseProjectEnvV1ProjectConfigEnvUsePostResponse = GenericResponse_str_

export type UseProjectEnvV1ProjectConfigEnvUsePostError = HTTPValidationError

export type GetProjectMetaConfigV1ProjectConfigMetaDetailGetData = {
  query: {
    project_id: string
  }
}

export type GetProjectMetaConfigV1ProjectConfigMetaDetailGetResponse = ModuleConfigResponse

export type GetProjectMetaConfigV1ProjectConfigMetaDetailGetError = HTTPValidationError

export type GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetData = {
  query: {
    project_id: string
  }
}

export type GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetResponse = ModuleConfigResponse

export type GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetError = HTTPValidationError

export type GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetData = {
  query: {
    project_id: string
  }
}

export type GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetResponse =
  ModuleConfigResponse

export type GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetError =
  HTTPValidationError

export type UpdateProjectConfigV1ProjectConfigUpdatePostData = {
  body: ModuleConfigUpdateRequest
  query: {
    module_type: ModuleType | ConfigType
    project_id: string
  }
}

export type UpdateProjectConfigV1ProjectConfigUpdatePostResponse = GenericResponse_str_

export type UpdateProjectConfigV1ProjectConfigUpdatePostError = HTTPValidationError

export type CreateProjectV1ProjectCreatePostData = {
  body: CreateProjectData
}

export type CreateProjectV1ProjectCreatePostResponse = GenericResponse_str_

export type CreateProjectV1ProjectCreatePostError = HTTPValidationError

export type AddProjectV1ProjectAddPostData = {
  body: AddProjectData
}

export type AddProjectV1ProjectAddPostResponse = GenericResponse_str_

export type AddProjectV1ProjectAddPostError = HTTPValidationError

export type GetProjectProfileV1ProjectProfileGetData = {
  query: {
    project_id: string
  }
}

export type GetProjectProfileV1ProjectProfileGetResponse = GenericResponse_NoneBotProjectMeta_

export type GetProjectProfileV1ProjectProfileGetError = HTTPValidationError

export type DeleteProjectV1ProjectDeleteDeleteData = {
  query: {
    delete_fully?: boolean
    project_id: string
  }
}

export type DeleteProjectV1ProjectDeleteDeleteResponse = GenericResponse_str_

export type DeleteProjectV1ProjectDeleteDeleteError = HTTPValidationError

export type ListProjectV1ProjectListGetResponse = ListProjectResponse

export type ListProjectV1ProjectListGetError = unknown

export type CheckProjectTomlV1ProjectCheckTomlPostData = {
  query: {
    project_dir: string
  }
}

export type CheckProjectTomlV1ProjectCheckTomlPostResponse = GenericResponse_ProjectTomlDetail_

export type CheckProjectTomlV1ProjectCheckTomlPostError = HTTPValidationError
